### ISSUE TITLE
d2l-skeletize-paragraph does not support RTL

### ISSUE THREAD

**Issue by rebeccazhou0727** [BrightspaceUI/core#1069]
None of the paragraph skeletons currently supports RTL.

![image](https://user-images.githubusercontent.com/46351616/105759778-d4df6580-5f1e-11eb-8d0f-54d36785a87b.png)

**Comment by svanherk** [comment]
I asked @rebeccazhou0727 to post this here in case others have more context - was this skipped on purpose?

**Comment by dbatiste** [comment]
I don't _think_ this was intentional.  We probably didn't notice this because it's baked into the encoded image.  We can either provide a new image for the RTL case, or we can take a similar [approach as icons](https://github.com/BrightspaceUI/core/blob/master/components/icons/icon-styles.js#L34) and flip the image with a transform by multiplying by `-1` on the x-axis.

```css
:host([skeleton][dir="rtl"]) .d2l-skeletize-paragraph-2 {
    -webkit-transform: scale(-1, 1);
    transform: scale(-1, 1);
    transform-origin: center;
}
```

I'm uncertain as to which way is better.  On one hand, more images bloats the CSS more.  On the other hand, a transform is more work the browser needs to do.  Ultimately it might not make much difference, in which case it may be nice to just maintain a single image and do the transform.

Also, might be able to get rid of the `-webkit-` - need to check that.
